### ISSUE TITLE
Enable an accounting check-and-balance that insures what’s reported as collected by the machine is in fact what has been collected by the Maintainer.

### ISSUE THREAD

**Issue by leanayan** [jinxiang/vmcs#3]
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors.

Current System:
![image](https://user-images.githubusercontent.com/18295563/30190749-e82cbfda-946e-11e7-8802-bb61e6626eaf.png)

Requested Enhancement:
![image](https://user-images.githubusercontent.com/18295563/30190769-08a42e4c-946f-11e7-995f-854375a34ad2.png)

**Comment by nguwarthawdarshwe** [comment]
Have done verification on enhancement and Test result is Pass with actual result captured as below.

Have done review on design model report.

![screen shot 2017-09-10 at 01 30 28](https://user-images.githubusercontent.com/8455390/30238978-e9ce6714-9584-11e7-90d9-cb98d25c7a8a.png)

**Comment by leanayan** [comment]
Verified OK - The denomination quantity and amount tally with the Total Cash Held and total Coins to Collect
