### ISSUE TITLE
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushes “Press Here When Finished”. 

### ISSUE THREAD

**Issue by leanayan** [jinxiang/vmcs#4]
The simulation currently does not clear the values on the completion of a Maintenance session. Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected, persists in display. 

Current System - Identified Defect:
![image](https://user-images.githubusercontent.com/18295563/30190825-70325034-946f-11e7-967c-40727d702747.png)

Expected Fix:
![image](https://user-images.githubusercontent.com/18295563/30190840-8a4786d8-946f-11e7-9504-67eac540bc9d.png)

**Comment by nguwarthawdarshwe** [comment]
Have Done verification for bugs as shown in below screenshots captured.

![screen shot 2017-09-10 at 01 13 47](https://user-images.githubusercontent.com/8455390/30238927-e1f30d34-9583-11e7-926d-c01d2854191b.png)
![screen shot 2017-09-10 at 01 13 32](https://user-images.githubusercontent.com/8455390/30238930-e1f4cb88-9583-11e7-9b84-bf01612c6594.png)
![screen shot 2017-09-10 at 01 12 56](https://user-images.githubusercontent.com/8455390/30238929-e1f4c19c-9583-11e7-9914-0802761905d4.png)
![screen shot 2017-09-10 at 01 12 42](https://user-images.githubusercontent.com/8455390/30238928-e1f4b314-9583-11e7-99af-21b3269a8903.png)

**Comment by leanayan** [comment]
Verified OK - On completion of session, the data of the previous session are reset to null
